# Generated by Django 6.0.5 on 2026-06-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='telefone',
        ),
    ]
